[nfs]
172.31.80.22 ansible_ssh_user='ec2-user'

[webservers]
172.31.83.203 ansible_ssh_user='ec2-user'
172.31.80.186 ansible_ssh_user='ec2-user'

[db]
172.31.91.40 ansible_ssh_user='unbuntu' 

[lb]
172.31.85.14 ansible_ssh_user='ubuntu'